# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='shop',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='shop',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='deal',
            field=models.CharField(max_length=20, verbose_name='商品销量'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.CharField(max_length=200, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=50, verbose_name='商店地址'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop',
            field=models.CharField(max_length=50, verbose_name='商店名称'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
    ]
