# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200419_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='商品状态'),
        ),
        migrations.AddField(
            model_name='shop',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='商品库存'),
        ),
    ]
