# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200419_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='stock',
        ),
    ]
