# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shop_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='stock',
            field=models.IntegerField(default=100, verbose_name='商品库存'),
        ),
    ]
