# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='stock',
        ),
    ]
