# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-21 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_shop_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='stock',
            field=models.IntegerField(default=100, verbose_name='商品库存'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.CharField(max_length=20, verbose_name='商品价格'),
        ),
    ]
