# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-17 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('series', models.CharField(max_length=50)),
            ],
        ),
    ]
