# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('series', models.CharField(max_length=50, verbose_name='分类')),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
            },
        ),
    ]
