# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200118_1301'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '菜谱', 'verbose_name_plural': '菜谱'},
        ),
        migrations.AddField(
            model_name='item',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='贡献者'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='series',
            field=models.CharField(max_length=50, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
