# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-25 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200118_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
    ]
