# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-28 11:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
