# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-17 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='收藏/取消时间')),
                ('status', models.BooleanField(default=True, verbose_name='收藏状态')),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('series', models.CharField(max_length=50, verbose_name='分类')),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='index.Item', verbose_name='菜谱'),
        ),
    ]
